// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"EffekseerForRPGMakerMZ_Ex","status":true,"description":"Effekseer 拡張プラグイン v1.70e - 1.05","parameters":{"InstanceMaxCount":"10000","SquareMaxCount":"10000","DistortionEnabled":"false"}},
{"name":"MPP_ChoiceEX","status":true,"description":"選択肢の機能を拡張します。","parameters":{"Max Page Row":"12","Disabled Position":"none","Choice Help Commands":"[\"ChoiceHelp\",\"<ChoiceHelp>\",\"選択肢ヘルプ\",\"<選択肢ヘルプ>\"]"}}
];
